/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeritoIndexRouteImport } from './routes/perito.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AbogadoIndexRouteImport } from './routes/abogado.index'
import { Route as PeritoPerfilRouteImport } from './routes/perito.perfil'
import { Route as PeritoCalendarioRouteImport } from './routes/perito.calendario'
import { Route as PeritoAyudaIaRouteImport } from './routes/perito.ayuda-ia'
import { Route as ClienteRegistroRouteImport } from './routes/cliente.registro'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as ApiSendLeadEmailRouteImport } from './routes/api.send-lead-email'
import { Route as ApiNotifyDocsCompletosRouteImport } from './routes/api.notify-docs-completos'
import { Route as ApiNotifyDocRechazadoRouteImport } from './routes/api.notify-doc-rechazado'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminPlantillasRouteImport } from './routes/admin.plantillas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInformesRouteImport } from './routes/admin.informes'
import { Route as AdminFinanzasRouteImport } from './routes/admin.finanzas'
import { Route as AdminDespachosRouteImport } from './routes/admin.despachos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminCasosRouteImport } from './routes/admin.casos'
import { Route as AbogadoPerfilRouteImport } from './routes/abogado.perfil'
import { Route as AbogadoCalendarioRouteImport } from './routes/abogado.calendario'
import { Route as AbogadoAyudaIaRouteImport } from './routes/abogado.ayuda-ia'
import { Route as AdminConfiguracionEmailRouteImport } from './routes/admin.configuracion.email'
import { Route as AdminCasosIdRouteImport } from './routes/admin.casos_.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeritoIndexRoute = PeritoIndexRouteImport.update({
  id: '/perito/',
  path: '/perito/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbogadoIndexRoute = AbogadoIndexRouteImport.update({
  id: '/abogado/',
  path: '/abogado/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeritoPerfilRoute = PeritoPerfilRouteImport.update({
  id: '/perito/perfil',
  path: '/perito/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PeritoCalendarioRoute = PeritoCalendarioRouteImport.update({
  id: '/perito/calendario',
  path: '/perito/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const PeritoAyudaIaRoute = PeritoAyudaIaRouteImport.update({
  id: '/perito/ayuda-ia',
  path: '/perito/ayuda-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRegistroRoute = ClienteRegistroRouteImport.update({
  id: '/cliente/registro',
  path: '/cliente/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/cliente/login',
  path: '/cliente/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendLeadEmailRoute = ApiSendLeadEmailRouteImport.update({
  id: '/api/send-lead-email',
  path: '/api/send-lead-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyDocsCompletosRoute = ApiNotifyDocsCompletosRouteImport.update({
  id: '/api/notify-docs-completos',
  path: '/api/notify-docs-completos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyDocRechazadoRoute = ApiNotifyDocRechazadoRouteImport.update({
  id: '/api/notify-doc-rechazado',
  path: '/api/notify-doc-rechazado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlantillasRoute = AdminPlantillasRouteImport.update({
  id: '/admin/plantillas',
  path: '/admin/plantillas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInformesRoute = AdminInformesRouteImport.update({
  id: '/admin/informes',
  path: '/admin/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanzasRoute = AdminFinanzasRouteImport.update({
  id: '/admin/finanzas',
  path: '/admin/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDespachosRoute = AdminDespachosRouteImport.update({
  id: '/admin/despachos',
  path: '/admin/despachos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/admin/configuracion',
  path: '/admin/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasosRoute = AdminCasosRouteImport.update({
  id: '/admin/casos',
  path: '/admin/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const AbogadoPerfilRoute = AbogadoPerfilRouteImport.update({
  id: '/abogado/perfil',
  path: '/abogado/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AbogadoCalendarioRoute = AbogadoCalendarioRouteImport.update({
  id: '/abogado/calendario',
  path: '/abogado/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AbogadoAyudaIaRoute = AbogadoAyudaIaRouteImport.update({
  id: '/abogado/ayuda-ia',
  path: '/abogado/ayuda-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionEmailRoute = AdminConfiguracionEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminConfiguracionRoute,
} as any)
const AdminCasosIdRoute = AdminCasosIdRouteImport.update({
  id: '/admin/casos_/$id',
  path: '/admin/casos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abogado/ayuda-ia': typeof AbogadoAyudaIaRoute
  '/abogado/calendario': typeof AbogadoCalendarioRoute
  '/abogado/perfil': typeof AbogadoPerfilRoute
  '/admin/casos': typeof AdminCasosRoute
  '/admin/configuracion': typeof AdminConfiguracionRouteWithChildren
  '/admin/despachos': typeof AdminDespachosRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/informes': typeof AdminInformesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plantillas': typeof AdminPlantillasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/notify-doc-rechazado': typeof ApiNotifyDocRechazadoRoute
  '/api/notify-docs-completos': typeof ApiNotifyDocsCompletosRoute
  '/api/send-lead-email': typeof ApiSendLeadEmailRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/perito/ayuda-ia': typeof PeritoAyudaIaRoute
  '/perito/calendario': typeof PeritoCalendarioRoute
  '/perito/perfil': typeof PeritoPerfilRoute
  '/abogado/': typeof AbogadoIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/perito/': typeof PeritoIndexRoute
  '/admin/casos/$id': typeof AdminCasosIdRoute
  '/admin/configuracion/email': typeof AdminConfiguracionEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abogado/ayuda-ia': typeof AbogadoAyudaIaRoute
  '/abogado/calendario': typeof AbogadoCalendarioRoute
  '/abogado/perfil': typeof AbogadoPerfilRoute
  '/admin/casos': typeof AdminCasosRoute
  '/admin/configuracion': typeof AdminConfiguracionRouteWithChildren
  '/admin/despachos': typeof AdminDespachosRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/informes': typeof AdminInformesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plantillas': typeof AdminPlantillasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/notify-doc-rechazado': typeof ApiNotifyDocRechazadoRoute
  '/api/notify-docs-completos': typeof ApiNotifyDocsCompletosRoute
  '/api/send-lead-email': typeof ApiSendLeadEmailRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/perito/ayuda-ia': typeof PeritoAyudaIaRoute
  '/perito/calendario': typeof PeritoCalendarioRoute
  '/perito/perfil': typeof PeritoPerfilRoute
  '/abogado': typeof AbogadoIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/perito': typeof PeritoIndexRoute
  '/admin/casos/$id': typeof AdminCasosIdRoute
  '/admin/configuracion/email': typeof AdminConfiguracionEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abogado/ayuda-ia': typeof AbogadoAyudaIaRoute
  '/abogado/calendario': typeof AbogadoCalendarioRoute
  '/abogado/perfil': typeof AbogadoPerfilRoute
  '/admin/casos': typeof AdminCasosRoute
  '/admin/configuracion': typeof AdminConfiguracionRouteWithChildren
  '/admin/despachos': typeof AdminDespachosRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/informes': typeof AdminInformesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plantillas': typeof AdminPlantillasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/notify-doc-rechazado': typeof ApiNotifyDocRechazadoRoute
  '/api/notify-docs-completos': typeof ApiNotifyDocsCompletosRoute
  '/api/send-lead-email': typeof ApiSendLeadEmailRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/registro': typeof ClienteRegistroRoute
  '/perito/ayuda-ia': typeof PeritoAyudaIaRoute
  '/perito/calendario': typeof PeritoCalendarioRoute
  '/perito/perfil': typeof PeritoPerfilRoute
  '/abogado/': typeof AbogadoIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/perito/': typeof PeritoIndexRoute
  '/admin/casos_/$id': typeof AdminCasosIdRoute
  '/admin/configuracion/email': typeof AdminConfiguracionEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abogado/ayuda-ia'
    | '/abogado/calendario'
    | '/abogado/perfil'
    | '/admin/casos'
    | '/admin/configuracion'
    | '/admin/despachos'
    | '/admin/finanzas'
    | '/admin/informes'
    | '/admin/login'
    | '/admin/plantillas'
    | '/admin/usuarios'
    | '/api/notify-doc-rechazado'
    | '/api/notify-docs-completos'
    | '/api/send-lead-email'
    | '/cliente/login'
    | '/cliente/registro'
    | '/perito/ayuda-ia'
    | '/perito/calendario'
    | '/perito/perfil'
    | '/abogado/'
    | '/admin/'
    | '/cliente/'
    | '/perito/'
    | '/admin/casos/$id'
    | '/admin/configuracion/email'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abogado/ayuda-ia'
    | '/abogado/calendario'
    | '/abogado/perfil'
    | '/admin/casos'
    | '/admin/configuracion'
    | '/admin/despachos'
    | '/admin/finanzas'
    | '/admin/informes'
    | '/admin/login'
    | '/admin/plantillas'
    | '/admin/usuarios'
    | '/api/notify-doc-rechazado'
    | '/api/notify-docs-completos'
    | '/api/send-lead-email'
    | '/cliente/login'
    | '/cliente/registro'
    | '/perito/ayuda-ia'
    | '/perito/calendario'
    | '/perito/perfil'
    | '/abogado'
    | '/admin'
    | '/cliente'
    | '/perito'
    | '/admin/casos/$id'
    | '/admin/configuracion/email'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/abogado/ayuda-ia'
    | '/abogado/calendario'
    | '/abogado/perfil'
    | '/admin/casos'
    | '/admin/configuracion'
    | '/admin/despachos'
    | '/admin/finanzas'
    | '/admin/informes'
    | '/admin/login'
    | '/admin/plantillas'
    | '/admin/usuarios'
    | '/api/notify-doc-rechazado'
    | '/api/notify-docs-completos'
    | '/api/send-lead-email'
    | '/cliente/login'
    | '/cliente/registro'
    | '/perito/ayuda-ia'
    | '/perito/calendario'
    | '/perito/perfil'
    | '/abogado/'
    | '/admin/'
    | '/cliente/'
    | '/perito/'
    | '/admin/casos_/$id'
    | '/admin/configuracion/email'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbogadoAyudaIaRoute: typeof AbogadoAyudaIaRoute
  AbogadoCalendarioRoute: typeof AbogadoCalendarioRoute
  AbogadoPerfilRoute: typeof AbogadoPerfilRoute
  AdminCasosRoute: typeof AdminCasosRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRouteWithChildren
  AdminDespachosRoute: typeof AdminDespachosRoute
  AdminFinanzasRoute: typeof AdminFinanzasRoute
  AdminInformesRoute: typeof AdminInformesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlantillasRoute: typeof AdminPlantillasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ApiNotifyDocRechazadoRoute: typeof ApiNotifyDocRechazadoRoute
  ApiNotifyDocsCompletosRoute: typeof ApiNotifyDocsCompletosRoute
  ApiSendLeadEmailRoute: typeof ApiSendLeadEmailRoute
  ClienteLoginRoute: typeof ClienteLoginRoute
  ClienteRegistroRoute: typeof ClienteRegistroRoute
  PeritoAyudaIaRoute: typeof PeritoAyudaIaRoute
  PeritoCalendarioRoute: typeof PeritoCalendarioRoute
  PeritoPerfilRoute: typeof PeritoPerfilRoute
  AbogadoIndexRoute: typeof AbogadoIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  PeritoIndexRoute: typeof PeritoIndexRoute
  AdminCasosIdRoute: typeof AdminCasosIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perito/': {
      id: '/perito/'
      path: '/perito'
      fullPath: '/perito/'
      preLoaderRoute: typeof PeritoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abogado/': {
      id: '/abogado/'
      path: '/abogado'
      fullPath: '/abogado/'
      preLoaderRoute: typeof AbogadoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perito/perfil': {
      id: '/perito/perfil'
      path: '/perito/perfil'
      fullPath: '/perito/perfil'
      preLoaderRoute: typeof PeritoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perito/calendario': {
      id: '/perito/calendario'
      path: '/perito/calendario'
      fullPath: '/perito/calendario'
      preLoaderRoute: typeof PeritoCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perito/ayuda-ia': {
      id: '/perito/ayuda-ia'
      path: '/perito/ayuda-ia'
      fullPath: '/perito/ayuda-ia'
      preLoaderRoute: typeof PeritoAyudaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/registro': {
      id: '/cliente/registro'
      path: '/cliente/registro'
      fullPath: '/cliente/registro'
      preLoaderRoute: typeof ClienteRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/cliente/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-lead-email': {
      id: '/api/send-lead-email'
      path: '/api/send-lead-email'
      fullPath: '/api/send-lead-email'
      preLoaderRoute: typeof ApiSendLeadEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-docs-completos': {
      id: '/api/notify-docs-completos'
      path: '/api/notify-docs-completos'
      fullPath: '/api/notify-docs-completos'
      preLoaderRoute: typeof ApiNotifyDocsCompletosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-doc-rechazado': {
      id: '/api/notify-doc-rechazado'
      path: '/api/notify-doc-rechazado'
      fullPath: '/api/notify-doc-rechazado'
      preLoaderRoute: typeof ApiNotifyDocRechazadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plantillas': {
      id: '/admin/plantillas'
      path: '/admin/plantillas'
      fullPath: '/admin/plantillas'
      preLoaderRoute: typeof AdminPlantillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/informes': {
      id: '/admin/informes'
      path: '/admin/informes'
      fullPath: '/admin/informes'
      preLoaderRoute: typeof AdminInformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finanzas': {
      id: '/admin/finanzas'
      path: '/admin/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AdminFinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/despachos': {
      id: '/admin/despachos'
      path: '/admin/despachos'
      fullPath: '/admin/despachos'
      preLoaderRoute: typeof AdminDespachosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/casos': {
      id: '/admin/casos'
      path: '/admin/casos'
      fullPath: '/admin/casos'
      preLoaderRoute: typeof AdminCasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abogado/perfil': {
      id: '/abogado/perfil'
      path: '/abogado/perfil'
      fullPath: '/abogado/perfil'
      preLoaderRoute: typeof AbogadoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abogado/calendario': {
      id: '/abogado/calendario'
      path: '/abogado/calendario'
      fullPath: '/abogado/calendario'
      preLoaderRoute: typeof AbogadoCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abogado/ayuda-ia': {
      id: '/abogado/ayuda-ia'
      path: '/abogado/ayuda-ia'
      fullPath: '/abogado/ayuda-ia'
      preLoaderRoute: typeof AbogadoAyudaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion/email': {
      id: '/admin/configuracion/email'
      path: '/email'
      fullPath: '/admin/configuracion/email'
      preLoaderRoute: typeof AdminConfiguracionEmailRouteImport
      parentRoute: typeof AdminConfiguracionRoute
    }
    '/admin/casos_/$id': {
      id: '/admin/casos_/$id'
      path: '/admin/casos/$id'
      fullPath: '/admin/casos/$id'
      preLoaderRoute: typeof AdminCasosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminConfiguracionRouteChildren {
  AdminConfiguracionEmailRoute: typeof AdminConfiguracionEmailRoute
}

const AdminConfiguracionRouteChildren: AdminConfiguracionRouteChildren = {
  AdminConfiguracionEmailRoute: AdminConfiguracionEmailRoute,
}

const AdminConfiguracionRouteWithChildren =
  AdminConfiguracionRoute._addFileChildren(AdminConfiguracionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbogadoAyudaIaRoute: AbogadoAyudaIaRoute,
  AbogadoCalendarioRoute: AbogadoCalendarioRoute,
  AbogadoPerfilRoute: AbogadoPerfilRoute,
  AdminCasosRoute: AdminCasosRoute,
  AdminConfiguracionRoute: AdminConfiguracionRouteWithChildren,
  AdminDespachosRoute: AdminDespachosRoute,
  AdminFinanzasRoute: AdminFinanzasRoute,
  AdminInformesRoute: AdminInformesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlantillasRoute: AdminPlantillasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ApiNotifyDocRechazadoRoute: ApiNotifyDocRechazadoRoute,
  ApiNotifyDocsCompletosRoute: ApiNotifyDocsCompletosRoute,
  ApiSendLeadEmailRoute: ApiSendLeadEmailRoute,
  ClienteLoginRoute: ClienteLoginRoute,
  ClienteRegistroRoute: ClienteRegistroRoute,
  PeritoAyudaIaRoute: PeritoAyudaIaRoute,
  PeritoCalendarioRoute: PeritoCalendarioRoute,
  PeritoPerfilRoute: PeritoPerfilRoute,
  AbogadoIndexRoute: AbogadoIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  PeritoIndexRoute: PeritoIndexRoute,
  AdminCasosIdRoute: AdminCasosIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
